### PR TITLE
Use https in URL string for Maven central repo (#56)

### PR DESCRIPTION
**Pull request by fgrilli**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework8-migration-tool/57)

### CODE REVIEW

**Review by mkgl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework8-migration-tool/57)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @fgrilli)

___
*[src/main/java/com/vaadin/framework8/migrate/MavenResolver.java, line 32 at r1](https://reviewable.io/reviews/vaadin/framework8-migration-tool/57#-M2hDrtq5bBSXSsvv0r-:-M2hDrtr8n-kKWFYQLEJ:by24v3t) ([raw file](https://github.com/vaadin/framework8-migration-tool/blob/5c316f892248d581092b01f231ba523da2ae1c72/src/main/java/com/vaadin/framework8/migrate/MavenResolver.java#L32)):*
> ```Java
>     private static final List<RemoteRepository> repositories = Arrays.asList(
>             new RemoteRepository.Builder("central", "default",
>                     "https://repo1.maven.org/maven2/").build(),
> ```

Hey Rico, why repo1? Maven's [super POM](http://maven.apache.org/ref/3.6.3/maven-model-builder/super-pom.html) seems declares https://repo.maven.apache.org/maven2

**Comment by fgrilli** [comment]
> Hey Rico, why repo1? Maven's [super POM](http://maven.apache.org/ref/3.6.3/maven-model-builder/super-pom.html) seems declares https://repo.maven.apache.org/maven2

I think I found it at https://blog.sonatype.com/central-repository-moving-to-https  - looks like it is the same thing.

**Comment by fgrilli** [comment]
> > Hey Rico, why repo1? Maven's [super POM](http://maven.apache.org/ref/3.6.3/maven-model-builder/super-pom.html) seems declares https://repo.maven.apache.org/maven2
> 
> I think I found it at https://blog.sonatype.com/central-repository-moving-to-https - looks like it is the same thing.

Changed it anyway to `repo` - I guess it won't hurt anyway :)

**Comment by revoker** [comment]
Friendly reminder, it's still necessary to merge to master...

**Comment by Legioth** [comment]
Thanks for patiently waiting :)

Now we'll just have to figure out how to publish a new release for this project that nobody has touched in several years.

**Comment by Legioth** [comment]
Oh right, not releasing at all since we folded this functionality into the regular Maven plugin a good while ago.

**Pull request merged**
